(define (isort list cmp-fn)
  (define last (length list))
  (define (iter vec pos value)
    (let ((i (- pos 1)))
      (while (and (>= i 0) (cmp-fn (vector-ref vec i) value))
             (vector-set! vec (+ i 1) (vector-ref vec i))
             (set! i (- i 1)))
      (vector-set! vec (+ i 1) value)))
  (let ((i 1)
        (vec (list->vector list)))
    (while (< i last)
           (iter vec i (vector-ref vec i))
           (set! i (+ i 1)))
    (vector->list vec)))

(define (medsort list cmp-fn)
  (define (find v l r)
    )
  (define (select-median v l r)
    (vector-ref v (+ l 1)))
  (define (swap v a b)
    (let ((tmp (vector-ref v a)))
      (vector-set! v a (vector-ref v b))
      (vector-set! v b tmp)))
  (define (iter vec left right)
    (if (< left right)
        (let ((me (select-median vec left right))
              (mid (/ (+ left right) 2))
              (i left))
          (swap vec mid me)
          (while (< i (- mid 1))
                 (if (> (cmp-fn (vector-ref i) (vector-ref mid)) 0)
                     (let ((k (find vec mid right)))
                       (swap vec i k)))
                 (set! i (+ i 1)))
          (iter vec left (- mid 1))
          (iter vec (+ mid 1) right))))
  (let ((vec (list->vector list)))
    (iter vec 0 (- (length list) 1))
    (vector->list vec)))

(use gauche.test)
(test-start "sort")
(test-section "insert sort")
(define num-list '(3 9 6 5 1 9 4 7 4 1 2 0 2 4 1 5 0))
(define (numeric-cmp a b) (> a b))
(test* "num-list sort" '(0 0 1 1 1 2 2 3 4 4 4 5 5 6 7 9 9) (isort num-list numeric-cmp))
(set! num-list '(1 1 3 4 8 2 9 0 3 0 9 8 3 1 6 8))
(test* "num-list sort2" '(0 0 1 1 1 2 3 3 3 4 6 8 8 8 9 9) (isort num-list numeric-cmp))
(test-section "median sort")

(test-end)
